# Background and foreground colors
background = #eceed5
foreground = #1B2428

# Standard colors
palette = 0=#eceed5
palette = 1=#886500
palette = 2=#2c5618
palette = 3=#646304
palette = 4=#3665a2
palette = 5=#3366a2
palette = 6=#1d784a
palette = 7=#1B2428

# Bright colors
palette = 8=#7d7e77
palette = 9=#af8900
palette = 10=#487b23
palette = 11=#868800
palette = 12=#5687d5
palette = 13=#5388d5
palette = 14=#3b9f61
palette = 15=#384248
